# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(792, 572)
        Widget.setStyleSheet("* {\n"
"    color: white;\n"
"    background: transparent;\n"
"    font-size: 14pt;\n"
"    opacity: 0.1;\n"
"}\n"
"#appTitle {\n"
"    font-size: 30px;\n"
"    margin-bottom: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"#Widget {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background: #17181e;\n"
"}\n"
"QPushButton {\n"
"    color: gainsboro;\n"
"    position: relative;\n"
"    height: 36px;\n"
"    padding: 0 20px;\n"
"    margin: 6px;\n"
"    font-weight: 500;\n"
"    text-transform: uppercase;\n"
"    letter-spacing: 0.15em;\n"
"    border: none;\n"
"    background: #2d313c;\n"
"    border-radius: 3px;\n"
"}\n"
"QPushButton::hover {\n"
"    background: #535865;\n"
"}\n"
"QPushButton:disabled {\n"
"    color: #8a8d9f;\n"
"    background: #1d2029;\n"
"}\n"
"QListWidget {\n"
"    background: #2d313c;\n"
"    border-radius: 3px;\n"
"}\n"
"QListWidget::item {\n"
"    letter-spacing: normal;\n"
"    min-height: 48px;\n"
"    outline: none;\n"
"    position: relative;\n"
"}\n"
"QListWidget::item::hover {\n"
"    background: #3a3e49;\n"
"}\n"
"QListWidget::item:selected {\n"
"    background: #535865;\n"
"}\n"
"QPlainTextEdit {\n"
"    background: #2d313c;\n"
"    border-radius: 3px;\n"
"    padding: 10px;\n"
"    line-height: 40px;\n"
"}\n"
"QLineEdit {\n"
"    background: #2d313c;\n"
"    height: 36px;\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding-left: 5px;\n"
"}\n"
"QComboBox {\n"
"    background: #2d313c;\n"
"    color: white;\n"
"    height: 36px;\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"}\n"
"QSpinBox {\n"
"    background: #2d313c;\n"
"    color: white;\n"
"    height: 36px;\n"
"    border: 0;\n"
"    border-radius: 3px;\n"
"    padding-left: 5px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Widget)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.stackedPages = QtWidgets.QStackedWidget(Widget)
        self.stackedPages.setObjectName("stackedPages")
        self.homePage = QtWidgets.QWidget()
        self.homePage.setObjectName("homePage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.homePage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.appTitle = QtWidgets.QLabel(self.homePage)
        self.appTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.appTitle.setObjectName("appTitle")
        self.verticalLayout_2.addWidget(self.appTitle)
        self.bankList = QtWidgets.QListWidget(self.homePage)
        self.bankList.setStyleSheet("")
        self.bankList.setObjectName("bankList")
        self.verticalLayout_2.addWidget(self.bankList)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.enterTestButton = QtWidgets.QPushButton(self.homePage)
        self.enterTestButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enterTestButton.setStyleSheet("")
        self.enterTestButton.setObjectName("enterTestButton")
        self.horizontalLayout_8.addWidget(self.enterTestButton)
        spacerItem = QtWidgets.QSpacerItem(475, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.deleteBankButton = QtWidgets.QPushButton(self.homePage)
        self.deleteBankButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteBankButton.setStyleSheet("color: red")
        self.deleteBankButton.setObjectName("deleteBankButton")
        self.horizontalLayout_8.addWidget(self.deleteBankButton)
        self.editBankButton = QtWidgets.QPushButton(self.homePage)
        self.editBankButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.editBankButton.setObjectName("editBankButton")
        self.horizontalLayout_8.addWidget(self.editBankButton)
        self.addBankButton = QtWidgets.QPushButton(self.homePage)
        self.addBankButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addBankButton.setObjectName("addBankButton")
        self.horizontalLayout_8.addWidget(self.addBankButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.stackedPages.addWidget(self.homePage)
        self.editBankPage = QtWidgets.QWidget()
        self.editBankPage.setObjectName("editBankPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.editBankPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_8 = QtWidgets.QLabel(self.editBankPage)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.bankName = QtWidgets.QLineEdit(self.editBankPage)
        self.bankName.setObjectName("bankName")
        self.horizontalLayout_2.addWidget(self.bankName)
        self.bankSaveButton = QtWidgets.QPushButton(self.editBankPage)
        self.bankSaveButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bankSaveButton.setObjectName("bankSaveButton")
        self.horizontalLayout_2.addWidget(self.bankSaveButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.problemList = QtWidgets.QListWidget(self.editBankPage)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.problemList.setFont(font)
        self.problemList.setObjectName("problemList")
        self.verticalLayout_3.addWidget(self.problemList)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.homeButton = QtWidgets.QPushButton(self.editBankPage)
        self.homeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.homeButton.setObjectName("homeButton")
        self.horizontalLayout_3.addWidget(self.homeButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.deleteProblemButton = QtWidgets.QPushButton(self.editBankPage)
        self.deleteProblemButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.deleteProblemButton.setStyleSheet("color: red")
        self.deleteProblemButton.setObjectName("deleteProblemButton")
        self.horizontalLayout_3.addWidget(self.deleteProblemButton)
        self.editProblemButton = QtWidgets.QPushButton(self.editBankPage)
        self.editProblemButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.editProblemButton.setObjectName("editProblemButton")
        self.horizontalLayout_3.addWidget(self.editProblemButton)
        self.addProblemButton = QtWidgets.QPushButton(self.editBankPage)
        self.addProblemButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addProblemButton.setObjectName("addProblemButton")
        self.horizontalLayout_3.addWidget(self.addProblemButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.stackedPages.addWidget(self.editBankPage)
        self.editProblemPage = QtWidgets.QWidget()
        self.editProblemPage.setObjectName("editProblemPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.editProblemPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setContentsMargins(-1, -1, 0, -1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_6 = QtWidgets.QLabel(self.editProblemPage)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 0, 1, 1)
        self.problemType = QtWidgets.QComboBox(self.editProblemPage)
        self.problemType.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.problemType.setObjectName("problemType")
        self.problemType.addItem("")
        self.problemType.addItem("")
        self.problemType.addItem("")
        self.gridLayout_6.addWidget(self.problemType, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.editProblemPage)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.editProblemPage)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 2, 0, 1, 1)
        self.problemAnswer = QtWidgets.QPlainTextEdit(self.editProblemPage)
        self.problemAnswer.setPlaceholderText("")
        self.problemAnswer.setObjectName("problemAnswer")
        self.gridLayout_6.addWidget(self.problemAnswer, 2, 1, 1, 1)
        self.problemText = QtWidgets.QPlainTextEdit(self.editProblemPage)
        self.problemText.setObjectName("problemText")
        self.gridLayout_6.addWidget(self.problemText, 1, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_6)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.backButton = QtWidgets.QPushButton(self.editProblemPage)
        self.backButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_11.addWidget(self.backButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.saveProblemButton = QtWidgets.QPushButton(self.editProblemPage)
        self.saveProblemButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveProblemButton.setObjectName("saveProblemButton")
        self.horizontalLayout_11.addWidget(self.saveProblemButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5.setStretch(0, 1)
        self.stackedPages.addWidget(self.editProblemPage)
        self.enterTestPage = QtWidgets.QWidget()
        self.enterTestPage.setObjectName("enterTestPage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.enterTestPage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setVerticalSpacing(25)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.enterTestPage)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.bankName_2 = QtWidgets.QLabel(self.enterTestPage)
        self.bankName_2.setText("")
        self.bankName_2.setObjectName("bankName_2")
        self.gridLayout_4.addWidget(self.bankName_2, 0, 1, 1, 1)
        self.testNum = QtWidgets.QSpinBox(self.enterTestPage)
        self.testNum.setProperty("value", 10)
        self.testNum.setObjectName("testNum")
        self.gridLayout_4.addWidget(self.testNum, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.enterTestPage)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 2, 0, 1, 1)
        self.problemNum = QtWidgets.QLabel(self.enterTestPage)
        self.problemNum.setText("")
        self.problemNum.setObjectName("problemNum")
        self.gridLayout_4.addWidget(self.problemNum, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.enterTestPage)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.homeButton_2 = QtWidgets.QPushButton(self.enterTestPage)
        self.homeButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.homeButton_2.setObjectName("homeButton_2")
        self.horizontalLayout_9.addWidget(self.homeButton_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.startTestButton = QtWidgets.QPushButton(self.enterTestPage)
        self.startTestButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startTestButton.setObjectName("startTestButton")
        self.horizontalLayout_9.addWidget(self.startTestButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.stackedPages.addWidget(self.enterTestPage)
        self.testPage = QtWidgets.QWidget()
        self.testPage.setObjectName("testPage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.testPage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_10 = QtWidgets.QLabel(self.testPage)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_10.setObjectName("label_10")
        self.gridLayout_9.addWidget(self.label_10, 2, 1, 1, 1)
        self.textProblemAnswer = QtWidgets.QPlainTextEdit(self.testPage)
        self.textProblemAnswer.setObjectName("textProblemAnswer")
        self.gridLayout_9.addWidget(self.textProblemAnswer, 2, 2, 1, 1)
        self.testProblemText = QtWidgets.QLabel(self.testPage)
        self.testProblemText.setObjectName("testProblemText")
        self.gridLayout_9.addWidget(self.testProblemText, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.testPage)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setObjectName("label_9")
        self.gridLayout_9.addWidget(self.label_9, 0, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_9)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.homeButton_3 = QtWidgets.QPushButton(self.testPage)
        self.homeButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.homeButton_3.setObjectName("homeButton_3")
        self.horizontalLayout_13.addWidget(self.homeButton_3)
        self.lookAnswerButton = QtWidgets.QPushButton(self.testPage)
        self.lookAnswerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lookAnswerButton.setObjectName("lookAnswerButton")
        self.horizontalLayout_13.addWidget(self.lookAnswerButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.currentNum = QtWidgets.QLabel(self.testPage)
        self.currentNum.setObjectName("currentNum")
        self.horizontalLayout_13.addWidget(self.currentNum)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.prevProblemButton = QtWidgets.QPushButton(self.testPage)
        self.prevProblemButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.prevProblemButton.setObjectName("prevProblemButton")
        self.horizontalLayout_13.addWidget(self.prevProblemButton)
        self.nextProblemButton = QtWidgets.QPushButton(self.testPage)
        self.nextProblemButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nextProblemButton.setObjectName("nextProblemButton")
        self.horizontalLayout_13.addWidget(self.nextProblemButton)
        self.submitButton = QtWidgets.QPushButton(self.testPage)
        self.submitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.submitButton.setObjectName("submitButton")
        self.horizontalLayout_13.addWidget(self.submitButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.stackedPages.addWidget(self.testPage)
        self.resultPage = QtWidgets.QWidget()
        self.resultPage.setObjectName("resultPage")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.resultPage)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem8)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setVerticalSpacing(25)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.problemWrongNum = QtWidgets.QLabel(self.resultPage)
        self.problemWrongNum.setText("")
        self.problemWrongNum.setObjectName("problemWrongNum")
        self.gridLayout_2.addWidget(self.problemWrongNum, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.resultPage)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.resultPage)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 0, 1, 1)
        self.problemRightNum = QtWidgets.QLabel(self.resultPage)
        self.problemRightNum.setText("")
        self.problemRightNum.setObjectName("problemRightNum")
        self.gridLayout_2.addWidget(self.problemRightNum, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.resultPage)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.problemLookNum = QtWidgets.QLabel(self.resultPage)
        self.problemLookNum.setText("")
        self.problemLookNum.setObjectName("problemLookNum")
        self.gridLayout_2.addWidget(self.problemLookNum, 2, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.homeButton_4 = QtWidgets.QPushButton(self.resultPage)
        self.homeButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.homeButton_4.setObjectName("homeButton_4")
        self.horizontalLayout_4.addWidget(self.homeButton_4)
        self.testAgainButton = QtWidgets.QPushButton(self.resultPage)
        self.testAgainButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.testAgainButton.setObjectName("testAgainButton")
        self.horizontalLayout_4.addWidget(self.testAgainButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.stackedPages.addWidget(self.resultPage)
        self.gridLayout.addWidget(self.stackedPages, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Widget)
        self.stackedPages.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.appTitle.setText(_translate("Widget", "Title"))
        self.enterTestButton.setText(_translate("Widget", "進入測驗"))
        self.deleteBankButton.setText(_translate("Widget", "刪除題庫"))
        self.editBankButton.setText(_translate("Widget", "編輯題庫"))
        self.addBankButton.setText(_translate("Widget", "新增題庫"))
        self.label_8.setText(_translate("Widget", "題庫名稱："))
        self.bankSaveButton.setText(_translate("Widget", "儲存"))
        self.homeButton.setText(_translate("Widget", "回首頁"))
        self.deleteProblemButton.setText(_translate("Widget", "刪除題目"))
        self.editProblemButton.setText(_translate("Widget", "編輯題目"))
        self.addProblemButton.setText(_translate("Widget", "新增題目"))
        self.label_6.setText(_translate("Widget", "題目敘述："))
        self.problemType.setItemText(0, _translate("Widget", "單選"))
        self.problemType.setItemText(1, _translate("Widget", "多選"))
        self.problemType.setItemText(2, _translate("Widget", "填充"))
        self.label_5.setText(_translate("Widget", "題目類型："))
        self.label_7.setText(_translate("Widget", "題目答案："))
        self.backButton.setText(_translate("Widget", "返回"))
        self.saveProblemButton.setText(_translate("Widget", "儲存"))
        self.label_2.setText(_translate("Widget", "題庫名稱："))
        self.label.setText(_translate("Widget", "測驗題數："))
        self.label_3.setText(_translate("Widget", "題庫題數："))
        self.homeButton_2.setText(_translate("Widget", "回首頁"))
        self.startTestButton.setText(_translate("Widget", "開始測驗"))
        self.label_10.setText(_translate("Widget", "作答"))
        self.testProblemText.setText(_translate("Widget", "1231134124312\n"
"2341241234123\n"
"12341341234123\n"
"2412341234123"))
        self.label_9.setText(_translate("Widget", "題目"))
        self.homeButton_3.setText(_translate("Widget", "終止測驗"))
        self.lookAnswerButton.setText(_translate("Widget", "查看答案"))
        self.currentNum.setText(_translate("Widget", "0"))
        self.prevProblemButton.setText(_translate("Widget", "上一題"))
        self.nextProblemButton.setText(_translate("Widget", "下一題"))
        self.submitButton.setText(_translate("Widget", "作答完畢"))
        self.label_4.setText(_translate("Widget", "答對題數："))
        self.label_12.setText(_translate("Widget", "答錯題數："))
        self.label_14.setText(_translate("Widget", "查看答案次數："))
        self.homeButton_4.setText(_translate("Widget", "回首頁"))
        self.testAgainButton.setText(_translate("Widget", "再次測驗"))
